# Following AWS resources will be made when ws_setup.sh is executed. 
# If you rather want to use the resources you've already had for running this
# sample application, please set the value bellow.

simulation_app_name: # Simulation application name. If you want to use specific name to the application, set the application name here.
robot_app_name: # Robot application name. If you want to use specific name to the application, set the application name here.
vpc: # VPC used for running simulator. If you want to use specific VPC, seth the VPC here. 
subnets: # subnets for running RoboMaker simulator. The subnets for the vpc are automatically defined. If you want to use specific subnets, set the subnets here. (with "- subnet" format).
security_groups: # security group used in RoboMaker simulator. This will be security group for default VPC.  If you want to use specific security group, set the security groups here. ( with "- secutiry-group-name" format).
